This is our grid search document! Note that there are some keyboard interrupts in our output, because we ran everything again just to make sure it works prior to our final submission! Because the full search takes a long time, we interrupted the kernel. The code works!

In [8]:
import tensorflow as tf
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.python.framework.errors_impl import InvalidArgumentError
import matplotlib.pyplot as plt

In [9]:
# Preprocessing + Training

# Load the dataset
df = pd.read_csv("../backend/Datasets/COALINDIA.csv")

# Feature selection and preprocessing
dropped_features = ['Date', 'Symbol', 'Series', 
                    'Trades', 'Turnover', 'Deliverable Volume', 
                    '%Deliverble', 'Last', 'VWAP', 'Prev Close']
df.drop(dropped_features, axis=1, inplace=True)

# Define features (X) and target (Y)
X = df.drop('Close', axis=1)
Y = df['Close']

# Scale the data
scaler_X = MinMaxScaler()
scaler_Y = MinMaxScaler()
X = scaler_X.fit_transform(X.values)
Y = scaler_Y.fit_transform(Y.values.reshape(-1, 1))

# Split the data into training and test sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42, shuffle=False)

print(f"X_train - {X_train}")
print("*" * 50)
print(f"X_test - {X_test}")
print("*" * 50)

print(f"Y_train - {Y_train}")
print("*" * 50)

print(f"Y_test - {Y_test}")


X_train - [[0.53912913 0.69460631 0.5541304  1.        ]
 [0.69474787 0.72926939 0.71293327 0.06651257]
 [0.72108335 0.72747647 0.6717056  0.09779414]
 ...
 [0.40011971 0.40475123 0.4025042  0.02255257]
 [0.40026934 0.39489018 0.38616583 0.04220904]
 [0.36465659 0.36261766 0.36784242 0.02943177]]
**************************************************
X_test - [[0.36555439 0.37950097 0.37196519 0.01550283]
 [0.37827323 0.38936202 0.38097419 0.01553931]
 [0.37572946 0.37546691 0.37883646 0.00991563]
 ...
 [0.05132426 0.05079934 0.05481753 0.01289286]
 [0.05656142 0.05259226 0.05527561 0.01735301]
 [0.04952865 0.06618856 0.05329058 0.0570686 ]]
**************************************************
Y_train - [[0.69701067]
 [0.71894247]
 [0.66155926]
 ...
 [0.39762656]
 [0.37990086]
 [0.36472886]]
**************************************************
Y_test - [[3.80501728e-01]
 [3.78248460e-01]
 [3.72239748e-01]
 [3.77196936e-01]
 [3.80501728e-01]
 [3.78098242e-01]
 [3.78098242e-01]
 [3.71188223e-01]

In [ ]:
def create_model_A(activation='relu', epochs=100, batch_size=32, op_learning_rate=1e-5, hidden=128, dropout=0.15):
    # Build a neural network model with 2 hidden layers
    # You can experiment with different architectures, including the number of layers and neurons.
    model = Sequential()
    model.add(Dense(64, input_dim=X_train.shape[1], activation='relu'))
    model.add(Dense(hidden, activation='relu'))
    model.add(Dropout(dropout))
    model.add(Dense(1))

    # Compile the model
    optimizer = Adam(learning_rate=op_learning_rate)  # Experiment with learning rate
    model.compile(optimizer=optimizer, loss='mean_squared_error')

    # Train the model
    history = model.fit(X_train, Y_train, epochs=100, batch_size=32, validation_data=(X_test, Y_test), verbose=0)

    # Make predictions
    Y_pred = model.predict(X_test)

    # Inverse transform the scaled values
    Y_test_original = scaler_Y.inverse_transform(Y_test)
    Y_pred_original = scaler_Y.inverse_transform(Y_pred)

    print(f"Activation: {activation}\nEpoch: {epochs}\nBatch Size: {batch_size}\nOptimizer learning rate: {op_learning_rate}")
    print(f"Hidden: {hidden}\nDropout: {dropout}")
    # Calculate MSE and R2
    mse = mean_squared_error(Y_test_original, Y_pred_original)
    print(f"Mean Squared Error: {mse}")
    metric = tf.keras.metrics.R2Score()
    metric.update_state(Y_test_original, Y_pred_original)
    r2 = metric.result().numpy()
    print("R^2:", metric.result().numpy())
    print("-"*64)
    return mse, r2

In [ ]:
ret = []
for activation in ['relu', 'sigmoid', 'tanh']:
    for epochs in [50, 75, 100, 150]:
        for batch_size in [24, 32, 40]:
            for op_learning_rate in [1e-5, 1e-4, 1e-3]:
                for hidden in [32, 64, 128]:
                    for dropout in [0.05, 0.1, 0.15]:
                        try:
                            mse, r2 = create_model_A(activation=activation, epochs=epochs, batch_size=batch_size, op_learning_rate=op_learning_rate, hidden=hidden, dropout=dropout)
                            ret.append([activation, epochs, batch_size, op_learning_rate, hidden, dropout, mse, r2])
                        except InvalidArgumentError as e:
                            print("Model error with params")

    

In [ ]:
print("Best MSE for ANN:", sorted(ret, key=lambda x:x[-2])[0])
print("Best R^2 for ANN:", sorted(ret, key=lambda x:-x[-1])[0])

In [6]:
def create_model_P(activation=None, epochs=100, batch_size=32, op_learning_rate=1e-5):
    model = Sequential()
    model.add(Dense(1, input_dim=X_train.shape[1], activation=activation))

    # Compile the model
    optimizer = Adam(learning_rate=op_learning_rate)  # Experiment with learning rate
    model.compile(optimizer=optimizer, loss='mean_squared_error')

    # Train the model
    history = model.fit(X_train, Y_train, epochs=epochs, batch_size=batch_size, validation_data=(X_test, Y_test), verbose=0)

    # Make predictions
    Y_pred = model.predict(X_test)

    # Inverse transform the scaled values
    Y_test_original = scaler_Y.inverse_transform(Y_test)
    Y_pred_original = scaler_Y.inverse_transform(Y_pred)

    print(f"Activation: {activation}\nEpoch: {epochs}\nBatch Size: {batch_size}\nOptimizer learning rate: {op_learning_rate}")
    # Calculate MSE
    mse = mean_squared_error(Y_test_original, Y_pred_original)
    print(f"Mean Squared Error (Perceptron): {mse}")
    metric = tf.keras.metrics.R2Score()
    metric.update_state(Y_test_original, Y_pred_original)
    r2 = metric.result().numpy()
    print("R^2:", metric.result().numpy())
    print("-"*64)
    return mse, r2


In [10]:
ret = []
for activation in [None, 'relu', 'sigmoid', 'tanh']:
    for epochs in [50, 75, 100, 150]:
        for batch_size in [24, 32, 40]:
            for op_learning_rate in [1e-5, 1e-4, 1e-3]:
                try:
                    mse, r2 = create_model_P(activation=activation, epochs=epochs, batch_size=batch_size, op_learning_rate=op_learning_rate)
                    ret.append([activation, epochs, batch_size, op_learning_rate, mse, r2])
                except InvalidArgumentError as e:
                    print("Model error with params")


17/17 [==============================] - 0s 316us/step


Activation: None
Epoch: 50
Batch Size: 24
Optimizer learning rate: 1e-05
Mean Squared Error (Perceptron): 1392.6992577453946
R^2: 0.28688818
----------------------------------------------------------------
17/17 [==============================] - 0s 298us/step


Activation: None
Epoch: 50
Batch Size: 24
Optimizer learning rate: 0.0001
Mean Squared Error (Perceptron): 5276.005876701099
R^2: -1.7015038
----------------------------------------------------------------
17/17 [==============================] - 0s 275us/step


Activation: None
Epoch: 50
Batch Size: 24
Optimizer learning rate: 0.001
Mean Squared Error (Perceptron): 10.61555730477912
R^2: 0.9945645
----------------------------------------------------------------
17/17 [==============================] - 0s 327us/step


Activation: None
Epoch: 50
Batch Size: 32
Optimizer learning rate: 1e-05
Mean Squared Error (Perceptron): 526.2100493607261
R^2: 0.7305616
----------------------------------------------------------------
17/17 [==============================] - 0s 293us/step


Activation: None
Epoch: 50
Batch Size: 32
Optimizer learning rate: 0.0001
Mean Squared Error (Perceptron): 3655.665697347731
R^2: -0.87183154
----------------------------------------------------------------
17/17 [==============================] - 0s 304us/step


Activation: None
Epoch: 50
Batch Size: 32
Optimizer learning rate: 0.001
Mean Squared Error (Perceptron): 1120.4088516509232
R^2: 0.42631054
----------------------------------------------------------------
17/17 [==============================] - 0s 305us/step


Activation: None
Epoch: 50
Batch Size: 40
Optimizer learning rate: 1e-05
Mean Squared Error (Perceptron): 33099.950257835066
R^2: -15.94836
----------------------------------------------------------------
17/17 [==============================] - 0s 306us/step


Activation: None
Epoch: 50
Batch Size: 40
Optimizer learning rate: 0.0001
Mean Squared Error (Perceptron): 1814.1746798389825
R^2: 0.071077585
----------------------------------------------------------------
17/17 [==============================] - 0s 310us/step


Activation: None
Epoch: 50
Batch Size: 40
Optimizer learning rate: 0.001
Mean Squared Error (Perceptron): 7787.411109472357
R^2: -2.9874332
----------------------------------------------------------------
17/17 [==============================] - 0s 307us/step


Activation: None
Epoch: 75
Batch Size: 24
Optimizer learning rate: 1e-05
Mean Squared Error (Perceptron): 4747.144628804292
R^2: -1.4307077
----------------------------------------------------------------
17/17 [==============================] - 0s 289us/step


Activation: None
Epoch: 75
Batch Size: 24
Optimizer learning rate: 0.0001
Mean Squared Error (Perceptron): 134.3934579268669
R^2: 0.9311857
----------------------------------------------------------------
17/17 [==============================] - 0s 312us/step


Activation: None
Epoch: 75
Batch Size: 24
Optimizer learning rate: 0.001
Mean Squared Error (Perceptron): 17.441307086896416
R^2: 0.99106944
----------------------------------------------------------------


2023-12-08 10:50:57.072838: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at resource_variable_ops.cc:597 : INVALID_ARGUMENT: Cannot update variable with shape [] using a Tensor with shape [0], shapes must be equal.


Error encountered with configuration: Activation=None, Epochs=75, Batch size=32, Learning rate=1e-05, Hidden=128, Dropout=0.1
Graph execution error:

Detected at node AssignAddVariableOp defined at (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "/Users/nayeelimtiaz/anaconda3/lib/python3.11/site-packages/ipykernel_launcher.py", line 17, in <module>

  File "/Users/nayeelimtiaz/anaconda3/lib/python3.11/site-packages/traitlets/config/application.py", line 992, in launch_instance

  File "/Users/nayeelimtiaz/anaconda3/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 736, in start

  File "/Users/nayeelimtiaz/anaconda3/lib/python3.11/site-packages/tornado/platform/asyncio.py", line 195, in start

  File "/Users/nayeelimtiaz/anaconda3/lib/python3.11/asyncio/base_events.py", line 607, in run_forever

  File "/Users/nayeelimtiaz/anaconda3/lib/python3.11/asyncio/base_events.py", line 1922, in _

Activation: None
Epoch: 75
Batch Size: 32
Optimizer learning rate: 0.0001
Mean Squared Error (Perceptron): 7335.835654539274
R^2: -2.7562103
----------------------------------------------------------------
17/17 [==============================] - 0s 306us/step


Activation: None
Epoch: 75
Batch Size: 32
Optimizer learning rate: 0.001
Mean Squared Error (Perceptron): 9.957032419051583
R^2: 0.99490166
----------------------------------------------------------------
17/17 [==============================] - 0s 298us/step


Activation: None
Epoch: 75
Batch Size: 40
Optimizer learning rate: 1e-05
Mean Squared Error (Perceptron): 1810.6279869811517
R^2: 0.07289374
----------------------------------------------------------------
17/17 [==============================] - 0s 319us/step


Activation: None
Epoch: 75
Batch Size: 40
Optimizer learning rate: 0.0001
Mean Squared Error (Perceptron): 1483.8711772537729
R^2: 0.24020487
----------------------------------------------------------------
17/17 [==============================] - 0s 331us/step


Activation: None
Epoch: 75
Batch Size: 40
Optimizer learning rate: 0.001
Mean Squared Error (Perceptron): 3.71346282272757
R^2: 0.99809855
----------------------------------------------------------------
17/17 [==============================] - 0s 309us/step


Activation: None
Epoch: 100
Batch Size: 24
Optimizer learning rate: 1e-05
Mean Squared Error (Perceptron): 835.9634672686382
R^2: 0.57195675
----------------------------------------------------------------
17/17 [==============================] - 0s 302us/step


Activation: None
Epoch: 100
Batch Size: 24
Optimizer learning rate: 0.0001
Mean Squared Error (Perceptron): 9388.6670550963
R^2: -3.807334
----------------------------------------------------------------
17/17 [==============================] - 0s 307us/step


Activation: None
Epoch: 100
Batch Size: 24
Optimizer learning rate: 0.001
Mean Squared Error (Perceptron): 11.002858072570696
R^2: 0.99436617
----------------------------------------------------------------
17/17 [==============================] - 0s 287us/step


Activation: None
Epoch: 100
Batch Size: 32
Optimizer learning rate: 1e-05
Mean Squared Error (Perceptron): 1212.5172317297468
R^2: 0.3791477
----------------------------------------------------------------
17/17 [==============================] - 0s 296us/step


Activation: None
Epoch: 100
Batch Size: 32
Optimizer learning rate: 0.0001
Mean Squared Error (Perceptron): 2387.3827447311155
R^2: -0.22242534
----------------------------------------------------------------
17/17 [==============================] - 0s 355us/step


Activation: None
Epoch: 100
Batch Size: 32
Optimizer learning rate: 0.001
Mean Squared Error (Perceptron): 60.38625135158539
R^2: 0.9690801
----------------------------------------------------------------
17/17 [==============================] - 0s 319us/step


Activation: None
Epoch: 100
Batch Size: 40
Optimizer learning rate: 1e-05
Mean Squared Error (Perceptron): 11553.35814525464
R^2: -4.915733
----------------------------------------------------------------
17/17 [==============================] - 0s 343us/step


Activation: None
Epoch: 100
Batch Size: 40
Optimizer learning rate: 0.0001
Mean Squared Error (Perceptron): 995.0624885901668
R^2: 0.4904924
----------------------------------------------------------------
17/17 [==============================] - 0s 348us/step


Activation: None
Epoch: 100
Batch Size: 40
Optimizer learning rate: 0.001
Mean Squared Error (Perceptron): 3.880477842545045
R^2: 0.9980131
----------------------------------------------------------------
17/17 [==============================] - 0s 322us/step


Activation: None
Epoch: 150
Batch Size: 24
Optimizer learning rate: 1e-05
Mean Squared Error (Perceptron): 49202.762258153445
R^2: -24.193575
----------------------------------------------------------------
17/17 [==============================] - 0s 338us/step


Activation: None
Epoch: 150
Batch Size: 24
Optimizer learning rate: 0.0001
Mean Squared Error (Perceptron): 5473.365561160367
R^2: -1.8025589
----------------------------------------------------------------
17/17 [==============================] - 0s 297us/step


Activation: None
Epoch: 150
Batch Size: 24
Optimizer learning rate: 0.001
Mean Squared Error (Perceptron): 18.25527489125925
R^2: 0.9906526
----------------------------------------------------------------
17/17 [==============================] - 0s 321us/step


Activation: None
Epoch: 150
Batch Size: 32
Optimizer learning rate: 1e-05
Mean Squared Error (Perceptron): 1433.9118003965777
R^2: 0.26578575
----------------------------------------------------------------
17/17 [==============================] - 0s 309us/step


Activation: None
Epoch: 150
Batch Size: 32
Optimizer learning rate: 0.0001
Mean Squared Error (Perceptron): 6500.820077523151
R^2: -2.3286526
----------------------------------------------------------------
17/17 [==============================] - 0s 313us/step


Activation: None
Epoch: 150
Batch Size: 32
Optimizer learning rate: 0.001
Mean Squared Error (Perceptron): 9.936894215935757
R^2: 0.99491197
----------------------------------------------------------------
17/17 [==============================] - 0s 309us/step


Activation: None
Epoch: 150
Batch Size: 40
Optimizer learning rate: 1e-05
Mean Squared Error (Perceptron): 2887.0737877395077
R^2: -0.4782852
----------------------------------------------------------------
17/17 [==============================] - 0s 295us/step


Activation: None
Epoch: 150
Batch Size: 40
Optimizer learning rate: 0.0001
Mean Squared Error (Perceptron): 5.190241257969248
R^2: 0.9973424
----------------------------------------------------------------
17/17 [==============================] - 0s 323us/step


Activation: None
Epoch: 150
Batch Size: 40
Optimizer learning rate: 0.001
Mean Squared Error (Perceptron): 9.632463744796151
R^2: 0.99506783
----------------------------------------------------------------
17/17 [==============================] - 0s 310us/step


Activation: relu
Epoch: 50
Batch Size: 24
Optimizer learning rate: 1e-05
Mean Squared Error (Perceptron): 5368.853843415024
R^2: -1.7490454
----------------------------------------------------------------
17/17 [==============================] - 0s 311us/step


Activation: relu
Epoch: 50
Batch Size: 24
Optimizer learning rate: 0.0001
Mean Squared Error (Perceptron): 5389.570142197838
R^2: -1.7596531
----------------------------------------------------------------
17/17 [==============================] - 0s 314us/step


Activation: relu
Epoch: 50
Batch Size: 24
Optimizer learning rate: 0.001
Mean Squared Error (Perceptron): 25.630138153428938
R^2: 0.9868764
----------------------------------------------------------------
17/17 [==============================] - 0s 319us/step


Activation: relu
Epoch: 50
Batch Size: 32
Optimizer learning rate: 1e-05
Mean Squared Error (Perceptron): 5389.492935224799
R^2: -1.7596135
----------------------------------------------------------------
17/17 [==============================] - 0s 314us/step


Activation: relu
Epoch: 50
Batch Size: 32
Optimizer learning rate: 0.0001
Mean Squared Error (Perceptron): 2474.231562785094
R^2: -0.26689506
----------------------------------------------------------------
17/17 [==============================] - 0s 319us/step


Activation: relu
Epoch: 50
Batch Size: 32
Optimizer learning rate: 0.001
Mean Squared Error (Perceptron): 3.255831582301545
R^2: 0.9983329
----------------------------------------------------------------
17/17 [==============================] - 0s 315us/step


Activation: relu
Epoch: 50
Batch Size: 40
Optimizer learning rate: 1e-05
Mean Squared Error (Perceptron): 3574.4026401217
R^2: -0.830222
----------------------------------------------------------------
17/17 [==============================] - 0s 307us/step


Activation: relu
Epoch: 50
Batch Size: 40
Optimizer learning rate: 0.0001
Mean Squared Error (Perceptron): 5289.342693941913
R^2: -1.7083328
----------------------------------------------------------------
17/17 [==============================] - 0s 325us/step


Activation: relu
Epoch: 50
Batch Size: 40
Optimizer learning rate: 0.001
Mean Squared Error (Perceptron): 7.172784392739845
R^2: 0.9963273
----------------------------------------------------------------
17/17 [==============================] - 0s 294us/step


Activation: relu
Epoch: 75
Batch Size: 24
Optimizer learning rate: 1e-05
Mean Squared Error (Perceptron): 5389.574218676504
R^2: -1.759655
----------------------------------------------------------------
17/17 [==============================] - 0s 282us/step


Activation: relu
Epoch: 75
Batch Size: 24
Optimizer learning rate: 0.0001
Mean Squared Error (Perceptron): 2181.5107277699412
R^2: -0.11701155
----------------------------------------------------------------
17/17 [==============================] - 0s 327us/step


Activation: relu
Epoch: 75
Batch Size: 24
Optimizer learning rate: 0.001
Mean Squared Error (Perceptron): 16.383832942611626
R^2: 0.9916109
----------------------------------------------------------------
17/17 [==============================] - 0s 343us/step


Activation: relu
Epoch: 75
Batch Size: 32
Optimizer learning rate: 1e-05
Mean Squared Error (Perceptron): 2430.729021510376
R^2: -0.24462044
----------------------------------------------------------------
17/17 [==============================] - 0s 343us/step


Activation: relu
Epoch: 75
Batch Size: 32
Optimizer learning rate: 0.0001
Mean Squared Error (Perceptron): 5389.5954065814
R^2: -1.759666
----------------------------------------------------------------
17/17 [==============================] - 0s 301us/step


Activation: relu
Epoch: 75
Batch Size: 32
Optimizer learning rate: 0.001
Mean Squared Error (Perceptron): 5387.872756333625
R^2: -1.7587838
----------------------------------------------------------------
17/17 [==============================] - 0s 292us/step


Activation: relu
Epoch: 75
Batch Size: 40
Optimizer learning rate: 1e-05
Mean Squared Error (Perceptron): 493.7641629606643
R^2: 0.7471751
----------------------------------------------------------------
17/17 [==============================] - 0s 307us/step


Activation: relu
Epoch: 75
Batch Size: 40
Optimizer learning rate: 0.0001
Mean Squared Error (Perceptron): 441.276103794077
R^2: 0.77405083
----------------------------------------------------------------
17/17 [==============================] - 0s 333us/step


Activation: relu
Epoch: 75
Batch Size: 40
Optimizer learning rate: 0.001
Mean Squared Error (Perceptron): 5389.531350585034
R^2: -1.7596331
----------------------------------------------------------------
17/17 [==============================] - 0s 319us/step


Activation: relu
Epoch: 100
Batch Size: 24
Optimizer learning rate: 1e-05
Mean Squared Error (Perceptron): 389.36989672716555
R^2: 0.80062866
----------------------------------------------------------------
17/17 [==============================] - 0s 310us/step


Activation: relu
Epoch: 100
Batch Size: 24
Optimizer learning rate: 0.0001
Mean Squared Error (Perceptron): 5389.570137614477
R^2: -1.7596531
----------------------------------------------------------------
17/17 [==============================] - 0s 312us/step


Activation: relu
Epoch: 100
Batch Size: 24
Optimizer learning rate: 0.001
Mean Squared Error (Perceptron): 2.433506392215883
R^2: 0.99875396
----------------------------------------------------------------
17/17 [==============================] - 0s 325us/step


Activation: relu
Epoch: 100
Batch Size: 32
Optimizer learning rate: 1e-05
Mean Squared Error (Perceptron): 239.15731485424433
R^2: 0.8775429
----------------------------------------------------------------
17/17 [==============================] - 0s 351us/step


Activation: relu
Epoch: 100
Batch Size: 32
Optimizer learning rate: 0.0001
Mean Squared Error (Perceptron): 283.51645094510974
R^2: 0.85482943
----------------------------------------------------------------
17/17 [==============================] - 0s 344us/step


Activation: relu
Epoch: 100
Batch Size: 32
Optimizer learning rate: 0.001
Mean Squared Error (Perceptron): 11.748972324424662
R^2: 0.9939841
----------------------------------------------------------------
17/17 [==============================] - 0s 332us/step


Activation: relu
Epoch: 100
Batch Size: 40
Optimizer learning rate: 1e-05
Mean Squared Error (Perceptron): 82.16342980972803
R^2: 0.9579294
----------------------------------------------------------------
17/17 [==============================] - 0s 329us/step


Activation: relu
Epoch: 100
Batch Size: 40
Optimizer learning rate: 0.0001
Mean Squared Error (Perceptron): 559.3452738215096
R^2: 0.71359515
----------------------------------------------------------------
17/17 [==============================] - 0s 357us/step


Activation: relu
Epoch: 100
Batch Size: 40
Optimizer learning rate: 0.001
Mean Squared Error (Perceptron): 5389.570142197838
R^2: -1.7596531
----------------------------------------------------------------
17/17 [==============================] - 0s 345us/step


Activation: relu
Epoch: 150
Batch Size: 24
Optimizer learning rate: 1e-05
Mean Squared Error (Perceptron): 5389.5730225899215
R^2: -1.7596543
----------------------------------------------------------------
17/17 [==============================] - 0s 316us/step


Activation: relu
Epoch: 150
Batch Size: 24
Optimizer learning rate: 0.0001
Mean Squared Error (Perceptron): 47.98988943643656
R^2: 0.97542745
----------------------------------------------------------------
17/17 [==============================] - 0s 297us/step


Activation: relu
Epoch: 150
Batch Size: 24
Optimizer learning rate: 0.001
Mean Squared Error (Perceptron): 9.255369239807134
R^2: 0.9952609
----------------------------------------------------------------
17/17 [==============================] - 0s 278us/step


Activation: relu
Epoch: 150
Batch Size: 32
Optimizer learning rate: 1e-05
Mean Squared Error (Perceptron): 5363.505884613868
R^2: -1.7463071
----------------------------------------------------------------
17/17 [==============================] - 0s 342us/step


Activation: relu
Epoch: 150
Batch Size: 32
Optimizer learning rate: 0.0001
Mean Squared Error (Perceptron): 12.112428205060843
R^2: 0.993798
----------------------------------------------------------------


2023-12-08 10:54:09.333560: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at resource_variable_ops.cc:597 : INVALID_ARGUMENT: Cannot update variable with shape [] using a Tensor with shape [0], shapes must be equal.


Error encountered with configuration: Activation=relu, Epochs=150, Batch size=32, Learning rate=0.001, Hidden=128, Dropout=0.1
Graph execution error:

Detected at node AssignAddVariableOp defined at (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "/Users/nayeelimtiaz/anaconda3/lib/python3.11/site-packages/ipykernel_launcher.py", line 17, in <module>

  File "/Users/nayeelimtiaz/anaconda3/lib/python3.11/site-packages/traitlets/config/application.py", line 992, in launch_instance

  File "/Users/nayeelimtiaz/anaconda3/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 736, in start

  File "/Users/nayeelimtiaz/anaconda3/lib/python3.11/site-packages/tornado/platform/asyncio.py", line 195, in start

  File "/Users/nayeelimtiaz/anaconda3/lib/python3.11/asyncio/base_events.py", line 607, in run_forever

  File "/Users/nayeelimtiaz/anaconda3/lib/python3.11/asyncio/base_events.py", line 1922, in 

Activation: relu
Epoch: 150
Batch Size: 40
Optimizer learning rate: 1e-05
Mean Squared Error (Perceptron): 5389.570142197838
R^2: -1.7596531
----------------------------------------------------------------
17/17 [==============================] - 0s 325us/step


Activation: relu
Epoch: 150
Batch Size: 40
Optimizer learning rate: 0.0001
Mean Squared Error (Perceptron): 3057.0258355972737
R^2: -0.56530654
----------------------------------------------------------------
17/17 [==============================] - 0s 335us/step


Activation: relu
Epoch: 150
Batch Size: 40
Optimizer learning rate: 0.001
Mean Squared Error (Perceptron): 2.648684914167957
R^2: 0.99864376
----------------------------------------------------------------
17/17 [==============================] - 0s 304us/step


Activation: sigmoid
Epoch: 50
Batch Size: 24
Optimizer learning rate: 1e-05
Mean Squared Error (Perceptron): 13952.173082325944
R^2: -6.144012
----------------------------------------------------------------
17/17 [==============================] - 0s 333us/step


Activation: sigmoid
Epoch: 50
Batch Size: 24
Optimizer learning rate: 0.0001
Mean Squared Error (Perceptron): 11710.982347041985
R^2: -4.996442
----------------------------------------------------------------
17/17 [==============================] - 0s 291us/step


Activation: sigmoid
Epoch: 50
Batch Size: 24
Optimizer learning rate: 0.001
Mean Squared Error (Perceptron): 718.4272152062391
R^2: 0.63213956
----------------------------------------------------------------
17/17 [==============================] - 0s 297us/step


Activation: sigmoid
Epoch: 50
Batch Size: 32
Optimizer learning rate: 1e-05
Mean Squared Error (Perceptron): 14303.166718143548
R^2: -6.323734
----------------------------------------------------------------
17/17 [==============================] - 0s 317us/step


Activation: sigmoid
Epoch: 50
Batch Size: 32
Optimizer learning rate: 0.0001
Mean Squared Error (Perceptron): 18246.67138664089
R^2: -8.342949
----------------------------------------------------------------
17/17 [==============================] - 0s 357us/step


Activation: sigmoid
Epoch: 50
Batch Size: 32
Optimizer learning rate: 0.001
Mean Squared Error (Perceptron): 10352.260192431671
R^2: -4.3007274
----------------------------------------------------------------
17/17 [==============================] - 0s 332us/step


Activation: sigmoid
Epoch: 50
Batch Size: 40
Optimizer learning rate: 1e-05
Mean Squared Error (Perceptron): 12089.178251248231
R^2: -5.190092
----------------------------------------------------------------
17/17 [==============================] - 0s 331us/step


Activation: sigmoid
Epoch: 50
Batch Size: 40
Optimizer learning rate: 0.0001
Mean Squared Error (Perceptron): 18349.200473174562
R^2: -8.395447
----------------------------------------------------------------
17/17 [==============================] - 0s 331us/step


Activation: sigmoid
Epoch: 50
Batch Size: 40
Optimizer learning rate: 0.001
Mean Squared Error (Perceptron): 9595.110850560339
R^2: -3.9130406
----------------------------------------------------------------
17/17 [==============================] - 0s 344us/step


Activation: sigmoid
Epoch: 75
Batch Size: 24
Optimizer learning rate: 1e-05
Mean Squared Error (Perceptron): 14205.404203246266
R^2: -6.273676
----------------------------------------------------------------
17/17 [==============================] - 0s 323us/step


Activation: sigmoid
Epoch: 75
Batch Size: 24
Optimizer learning rate: 0.0001
Mean Squared Error (Perceptron): 23718.71296537388
R^2: -11.14483
----------------------------------------------------------------
17/17 [==============================] - 0s 307us/step


Activation: sigmoid
Epoch: 75
Batch Size: 24
Optimizer learning rate: 0.001
Mean Squared Error (Perceptron): 264.0992076105329
R^2: 0.8647717
----------------------------------------------------------------
17/17 [==============================] - 0s 310us/step


Activation: sigmoid
Epoch: 75
Batch Size: 32
Optimizer learning rate: 1e-05
Mean Squared Error (Perceptron): 11674.934144297082
R^2: -4.977984
----------------------------------------------------------------
17/17 [==============================] - 0s 304us/step


Activation: sigmoid
Epoch: 75
Batch Size: 32
Optimizer learning rate: 0.0001
Mean Squared Error (Perceptron): 21446.896449957138
R^2: -9.981579
----------------------------------------------------------------
17/17 [==============================] - 0s 325us/step


Activation: sigmoid
Epoch: 75
Batch Size: 32
Optimizer learning rate: 0.001
Mean Squared Error (Perceptron): 3146.6543093811956
R^2: -0.6111995
----------------------------------------------------------------
17/17 [==============================] - 0s 338us/step


Activation: sigmoid
Epoch: 75
Batch Size: 40
Optimizer learning rate: 1e-05
Mean Squared Error (Perceptron): 14022.4445768852
R^2: -6.179993
----------------------------------------------------------------
17/17 [==============================] - 0s 314us/step


Activation: sigmoid
Epoch: 75
Batch Size: 40
Optimizer learning rate: 0.0001
Mean Squared Error (Perceptron): 19261.420051346664
R^2: -8.862537
----------------------------------------------------------------
17/17 [==============================] - 0s 325us/step


Activation: sigmoid
Epoch: 75
Batch Size: 40
Optimizer learning rate: 0.001
Mean Squared Error (Perceptron): 1378.273430309472
R^2: 0.29427463
----------------------------------------------------------------
17/17 [==============================] - 0s 336us/step


Activation: sigmoid
Epoch: 100
Batch Size: 24
Optimizer learning rate: 1e-05
Mean Squared Error (Perceptron): 15430.521115378418
R^2: -6.9009786
----------------------------------------------------------------


KeyboardInterrupt: 

In [ ]:
print("Best MSE for Perceptron:", sorted(ret, key=lambda x:x[-2])[0])
print("Best R^2 for Perceptron:", sorted(ret, key=lambda x:-x[-1])[0])

In [ ]:
def create_model_D(activation='tanh', epochs=100, batch_size=32, op_learning_rate=1e-5, hidden=128, layers=11, dropout=0.1):
    # Build a neural network model with 2 hidden layers
    # You can experiment with different architectures, including the number of layers and neurons.
    # Building DNN model with 11 hidden layers
    model = Sequential()

    # Input layer
    # Input layer will have same number of neurons as number of feature variables
    model.add(Dense(64, input_dim=X_train.shape[1], activation=activation))

    # Hidden layers
    # Play around with number of neurons in each hidden layer.
    # Too many neurons leads to overcomplexity, not enough means too simple
    # Tanh activation function here is used b/c it is recommended to use
    # when there are more hidden layers.
    for _ in range(layers-1):
        model.add(Dense(hidden, activation=activation))
        model.add(Dropout(dropout)) # This helps with preventing overfitting

    # Output layer
    # Output layer will have 1 neuron b/c there's only 1 target variable
    model.add(Dense(1))

    # Compile the model
    optimizer = Adam(learning_rate=op_learning_rate)  # Experiment with learning rate
    model.compile(optimizer=optimizer, loss='mean_squared_error')

    # Train the model
    history = model.fit(X_train, Y_train, epochs=100, batch_size=32, validation_data=(X_test, Y_test), verbose=0)

    # Make predictions
    Y_pred = model.predict(X_test)

    # Inverse transform the scaled values
    Y_test_original = scaler_Y.inverse_transform(Y_test)
    Y_pred_original = scaler_Y.inverse_transform(Y_pred)

    print(f"Activation: {activation}\nEpoch: {epochs}\nBatch Size: {batch_size}\nOptimizer learning rate: {op_learning_rate}")
    print(f"Hidden: {hidden}\nLayers: {layers}\nDropout: {dropout}")
    # Calculate MSE and R2
    mse = mean_squared_error(Y_test_original, Y_pred_original)
    print(f"Mean Squared Error: {mse}")
    metric = tf.keras.metrics.R2Score()
    metric.update_state(Y_test_original, Y_pred_original)
    r2 = metric.result().numpy()
    print("R^2:", metric.result().numpy())
    print("-"*64)
    return mse, r2

In [ ]:
m, r = create_model_D()

In [ ]:
# GRID SEARCH

ret = []
for activation in ['relu', 'sigmoid', 'tanh']:
    for epochs in [50, 75, 100, 150]:
        for batch_size in [24, 32, 40]:
            for op_learning_rate in [1e-5, 1e-4, 1e-3]:
                for hidden in [32, 64, 128]:
                    for layers in [6, 9, 11]:
                        for dropout in [0.05, 0.1, 0.15]:
                            try:
                                mse, r2 = create_model_D(activation=activation, epochs=epochs, batch_size=batch_size, op_learning_rate=op_learning_rate, hidden=hidden, layers=layers, dropout=dropout)
                                ret.append([activation, epochs, batch_size, op_learning_rate, hidden, layers, dropout, mse, r2])
                            except:
                                print("Model error with params")



In [ ]:
print("Best MSE for DNN:", sorted(ret, key=lambda x:x[-2])[0])
print("Best R^2 for DNN:", sorted(ret, key=lambda x:-x[-1])[0])